### ISSUE TITLE
Gateway 23.99.160.139 decommissioned

### ISSUE THREAD

**Issue by Bafff** [Azure/SQL-Connectivity-Checker#51]
Gateway 23.99.160.139 for Central US is already decommissioned as far as I know https://azure.microsoft.com/ru-ru/updates/azure-sql-database-gateways-changes-centralus-september-15-2020/

**Comment by vitomaz-msft** [comment]
Thank you for reporting this issue @Bafff, the IP address is now removed. I'll follow-up internally on getting documentation aligned. Thank you!
