### ISSUE TITLE
Missing gateways. 

### ISSUE THREAD

**Issue by sodds-eq** [Azure/SQL-Connectivity-Checker#8]
There are several missing gateways from the script, which means it will always fail for those regions.
Ref. https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture#azure-sql-database-gateway-ip-addresses

So be aware of that if you try to use the script and it fails.

**Comment by vitomaz-msft** [comment]
Thanks for reporting this, a complete review was done at PR https://github.com/Azure/SQL-Connectivity-Checker/pull/19
Apologies for the long delay in our reply.
