### ISSUE TITLE
Gateway Address not valid

### ISSUE THREAD

**Issue by McGregsen** [Azure/SQL-Connectivity-Checker#97]
When testing an azure sql database that is running in redirect mode I get the following message:

`Detected as SQL Database/Azure Synapse`
`Trying to resolve DNS for xyz.database.windows.net`
`WARNING: 52.236.184.163 is not a valid gateway address ....`

When checking the [official documentation](https://docs.microsoft.com/azure/azure-sql/database/connectivity-architecture#gateway-ip-addresses) this is shown as a valid address for europe west. Also in the code in AzureSQLConnectivityChecker.ps1 the ip is present
`(    New-Object PSObject -Property @{Region = "West Europe"; Gateways = ("104.40.168.105", "52.236.184.163", "20.61.99.192", "20.61.99.193"); TRs = ('tr29', 'tr30', 'tr33', 'tr34'); Cluster = 'westeurope1-a.worker.database.windows.net'; })`
but the check fails anyway.

I am no powershell expert but it looks like the change in [commit](https://github.com/Azure/SQL-Connectivity-Checker/commit/78224975f375c2504ef2e89500ae70494ac1215c) introduced a syntax error in AzureSQLConnectivityChecker.ps1.

The `$SQLDBGateways = @(....)` Object only gets closed at the very end of the script file (strange that the script still works?!) It seems to only cause the check for the gateway IP to fail.
If I properly close the SQLDBGateways object on line 184 and remove the extra ")" at the end of the script: the detection of the ip works correctly.

**Comment by boxofyellow** [comment]
I also ran into this.  Sadly I did not notice the issue first, doing so would have saved me some time.

I'm not sure what the process if for getting changes merged but I created this with the hopes that someone with permission would merge it.
- https://github.com/Azure/SQL-Connectivity-Checker/pull/98
